name: text_formatters
description: A package of pre-build `TextInputFormatter` objects to use with Flutter's `TextField` or `TextFormField` widgets.
version: 1.0.1
author: Jeff Jorczak <jeff@jorczak.com>
homepage: https://github.com/codegrue/text_formatters

environment:
  sdk: ">=1.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  groovin_string_masks: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

# Steps to publish to pub.dartlang.org:
# 1) Run unit tests: "flutter test"
# 2) Verify no documentation issues: "dartdoc --no-auto-include-dependencies "
# 3) Verify no code issues: "flutter analyze"
# 3) Run dartpub review: "pana --verbosity compact"
# 4) Publish: "flutter packages pub publish"